# Generated by Django 5.2 on 2025-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', 'Yangiliklar'), ('projects', 'Loyihalar'), ('events', 'Tadbirlar'), ('announcements', 'E’lonlar'), ('grants', 'Grantlar'), ('articles', 'Maqolalar')], default='news', max_length=20),
        ),
    ]
